# fly.toml app configuration file generated for pma-nginx-fathcodes on 2024-07-26T07:51:09+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mypma'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  PMA_ARBITRARY = '1'
  UPLOAD_LIMIT = '50M'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
